// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBGmDhpyS0qVyYffPOLyGkn6bNhv6F85_I',
    appId: '1:674120639952:web:2f55ba6384ad0dcd8785d5',
    messagingSenderId: '674120639952',
    projectId: 'firebase-tutorial-230914',
    authDomain: 'fir-tutorial-230914.firebaseapp.com',
    storageBucket: 'firebase-tutorial-230914.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBaSCizCgU2tT7DLUMAwFZVyeQnoeoavt8',
    appId: '1:674120639952:android:5e48c430e176f8948785d5',
    messagingSenderId: '674120639952',
    projectId: 'firebase-tutorial-230914',
    storageBucket: 'firebase-tutorial-230914.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAfh0gqH8_nlH_hEG-B5iQo_TcxkRvZg0A',
    appId: '1:674120639952:ios:bfb2e7270f0374ff8785d5',
    messagingSenderId: '674120639952',
    projectId: 'firebase-tutorial-230914',
    storageBucket: 'firebase-tutorial-230914.appspot.com',
    iosBundleId: 'asano_mito.firebase_sample_230914',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAfh0gqH8_nlH_hEG-B5iQo_TcxkRvZg0A',
    appId: '1:674120639952:ios:df3d1c756d6d5ec78785d5',
    messagingSenderId: '674120639952',
    projectId: 'firebase-tutorial-230914',
    storageBucket: 'firebase-tutorial-230914.appspot.com',
    iosBundleId: 'asano_mito.firebase_sample_230914.RunnerTests',
  );
}
