// File generated by FlutterFire CLI.
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBGmDhpyS0qVyYffPOLyGkn6bNhv6F85_I',
    appId: '1:674120639952:web:2f55ba6384ad0dcd8785d5',
    messagingSenderId: '674120639952',
    projectId: 'firebase-tutorial-230914',
    authDomain: 'fir-tutorial-230914.firebaseapp.com',
    storageBucket: 'firebase-tutorial-230914.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBaSCizCgU2tT7DLUMAwFZVyeQnoeoavt8',
    appId: '1:674120639952:android:ac35b3bc7f0dc6af8785d5',
    messagingSenderId: '674120639952',
    projectId: 'firebase-tutorial-230914',
    storageBucket: 'firebase-tutorial-230914.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAfh0gqH8_nlH_hEG-B5iQo_TcxkRvZg0A',
    appId: '1:674120639952:ios:adbd2724484567398785d5',
    messagingSenderId: '674120639952',
    projectId: 'firebase-tutorial-230914',
    storageBucket: 'firebase-tutorial-230914.appspot.com',
    androidClientId: '674120639952-accseut3ahaf4vrff3s3c4a84rqu9h75.apps.googleusercontent.com',
    iosClientId: '674120639952-bbri5blsunrji5739lofsqlmsfdgb75l.apps.googleusercontent.com',
    iosBundleId: 'com.example.miToApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAfh0gqH8_nlH_hEG-B5iQo_TcxkRvZg0A',
    appId: '1:674120639952:ios:b39adc8db9daa4168785d5',
    messagingSenderId: '674120639952',
    projectId: 'firebase-tutorial-230914',
    storageBucket: 'firebase-tutorial-230914.appspot.com',
    androidClientId: '674120639952-accseut3ahaf4vrff3s3c4a84rqu9h75.apps.googleusercontent.com',
    iosClientId: '674120639952-le8248go8v2ereip9vohmnqv38fbdcpp.apps.googleusercontent.com',
    iosBundleId: 'com.example.miToApp.RunnerTests',
  );
}
